trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)

variables:
  nuget_package_number: '1.0.$(Build.BuildId)'

stages:
- stage: build
  displayName: build service and client package
  jobs:
  - job: Nuget
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'pack projects'
      inputs:
        command: 'pack'
        packagesToPack: 'src/Client/Client.csproj;src/PublicAPI/PublicAPI.csproj'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'nuget_package_number'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'emailservice-nuget'
        publishLocation: 'Container'

  - job: Backend
    steps:
    - task: Cake@2
      inputs:
        script: 'build.cake'
        target: 'PublishEmailService'
        verbosity: 'Verbose'
    - publish: deploy
      artifact: emailservice-build

- stage: pack
  displayName: Pack in docker image
  jobs:
    - job: pack_service
      displayName: Pack service
      steps:
        - download: current
          artifact: emailservice-build
        - task: Docker@2
          inputs:
            containerRegistry: 'rtuitlab connection by admin'
            repository: 'rtuitlab/emailservice'
            command: 'buildAndPush'
            Dockerfile: '$(Pipeline.Workspace)/emailservice-build/Dockerfile'
            buildContext: '$(Pipeline.Workspace)/emailservice-build'
            tags: |
              $(Build.BuildId)
              latest
